name: Update Samples

on:
  push:
    branches:
    - v3

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - name: Set name
      run: git config --global user.name "Robbot"
    - name: Set email
      run: git config --global user.email "robbot2019@robdangero.us"

    - name: Clone Samples
      run: git clone --branch v3 https://github.com/Kode/Kore-Samples.git
    - name: Get Kore-Submodule
      working-directory: Kore-Samples
      run: git submodule update --init --remote Kore
    - name: Checkout Kore
      working-directory: Kore-Samples/Kore
      run: git checkout v3
    - name: Add Kore
      working-directory: Kore-Samples
      run: git add Kore
    - name: Commit
      working-directory: Kore-Samples
      run: git commit -m "Update Kore"
    - name: Push
      working-directory: Kore-Samples
      run: git push https://Kode-Robbot:$ROBBOT_PASS@github.com/Kode/Kore-Samples.git
      env:
        ROBBOT_PASS: ${{ secrets.ROBBOT_PASS }}
      